name: Deploy Docs & Storybook

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'apps/document/**'
      - 'libs/react/**'
      - 'libs/core/**'
      - 'libs/source/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm & deps
        run: |
          npm install -g pnpm
          pnpm install

      - name: Sync TS project references
        run: pnpm nx sync --yes

      - name: Verify sync status (optional)
        run: pnpm nx sync:check

      - name: Build @aicody-ui/react (with deps)
        run: pnpm nx build @aicody-ui/react --with-deps
        env:
          NX_CLOUD: false

      - name: Build Docusaurus docs
        run: pnpm nx run document:build

      - name: Deploy docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./apps/document/build
          publish_branch: gh-pages

      - name: Build Storybook (with deps)
        run: pnpm nx run @aicody-ui/source:build-storybook --with-deps --outputDir=storybook-static
        env:
          NX_CLOUD: false

      - name: Deploy Storybook to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
          publish_branch: gh-pages
          destination_dir: storybook
          keep_files: true
